### ISSUE TITLE
Milestone4 discussion

### ISSUE THREAD

**Issue by nobbynguyen** [UBC-MDS/CryptocurrencyEDAr#39]
1. GITHUB: to add the following two workflows to R project
- https://github.com/r-lib/actions/blob/master/.github/workflows/check-standard.yaml
- https://github.com/r-lib/actions/blob/master/.github/workflows/test-coverage.yaml
—> successfully runs 2 workflows

2. Documentation for R Package: 
- Vignette
- pkgdown

3. Examine the license: open issues in R and Python package. Discuss and reason the license choice.

**Comment by alexYinanGu0** [comment]
Hi team, I have created issues to assign this week's tasks accordingly. Please give it a check!
